"""
build_index.py — generate models.json, the page's list of what exists.

    python3 build_index.py [--check]

The page must never be told which buildings exist. It fetches `models.json`
from a known path and renders whatever is in it, so adding Laurel is a row of
data rather than an edit to the viewer.

WHAT THIS SCANS, AND WHY IT IS NOT THE SPECS. One model per directory under
`models/`, and a model counts as PUBLISHED when it has `export/variants.json`
-- the artefact `finish_adu.py` only writes after its own gates pass. A model
whose export failed, or that has never been exported, is not in the index and
should not be: the page would offer a card that cannot load.

WHAT A VALID MANIFEST AND ROW ARE is not decided here. `model_contract.py`
decides, and `finish_adu.py` and `verify_index.py` import the same checks.

The index lives at `prototype/models.json`, beside the page that fetches it
(docs/PAGE-PLAN.md). Every path published here is relative to THAT directory
-- so `../models/<id>/...` -- because a relative path with no stated origin is
a path that works on one machine. The paths climb out of `prototype/`, so
whatever serves the page must serve `buyer/3D` as its root.

Run with `--check` to compare the index on disk against a fresh scan without
writing. That is what `verify_index.py` calls, and it is the whole point: the
index is a COMMITTED artefact, so the failure mode is not a bad scan, it is a
STALE FILE -- somebody added a model and did not re-run this.
"""
import json
import os
import sys
from pathlib import Path

import model_contract

HERE = Path(__file__).resolve().parent
MODELS = HERE / "models"
INDEX = HERE / "prototype" / "models.json"

NOTE = (
    "GENERATED BY build_index.py -- do not hand-edit. A model appears here "
    "when it has export/variants.json, which finish_adu.py writes only after "
    "its gates pass. Paths are relative to this file. `levels` is ordered "
    "coarsest-last: lod0 is full detail, lod2 is massing only. `primary` is "
    "the unsuffixed .glb, a copy of lod0, kept for anyone who wants one file."
)


def levels_for(export: Path, model_id: str):
    """The .glb files this model actually shipped, classified by name.

    READ OFF DISK RATHER THAN OFF THE SPEC. The spec's `lod.levels` block
    says what SHOULD exist; this index is a promise that a URL resolves, and
    only the directory can make that promise. A spec that declares lod3 and
    an export that never wrote it would otherwise publish a 404.

    REGULAR FILES ONLY, AND ONLY NAMES THE PAGE CAN INTERPRET. A directory
    named `x.glb` matches the glob and cannot be fetched. `<id>.glb` is the
    primary and `<id>_lod<N>.glb` a level; any other `<id>_*.glb` is a level
    the page could not choose, so it fails the build. A .glb not named for
    this model at all is not this index's business and is left alone.
    """
    found, primary = {}, None
    for glb in sorted(p for p in export.glob("*.glb") if p.is_file()):
        stem = glb.stem
        if stem == model_id:
            primary = glb
        elif stem.startswith(model_id + "_"):
            level = stem[len(model_id) + 1:]
            if not model_contract.LEVEL_NAME.match(level):
                raise SystemExit(
                    f"models.json: {glb} is neither `{model_id}.glb` nor "
                    f"`{model_id}_lod<N>.glb`; the page cannot tell which "
                    f"level it is")
            found[level] = glb
    return found, primary


def scan():
    rows, seen = [], {}
    if not MODELS.is_dir():
        return rows
    for d in sorted(p for p in MODELS.iterdir() if p.is_dir()):
        manifest = d / "export" / "variants.json"
        if not manifest.is_file():
            continue
        try:
            m = json.loads(manifest.read_text())
        except (ValueError, OSError) as e:
            # ANYTHING READ FROM DISK IS UNTRUSTED INPUT, INCLUDING OUR OWN
            # FILES (rule 25). A half-written manifest must fail loudly here
            # rather than produce a row with holes in it.
            raise SystemExit(f"models.json: {manifest} is unreadable: {e}")

        if not isinstance(m, dict):
            raise SystemExit(
                f"models.json: {manifest} is valid JSON but its root is a "
                f"{type(m).__name__}, not an object")

        # THE WHOLE IDENTITY BLOCK, BEFORE ANY OF IT IS USED. There is no
        # fallback to the directory name for a missing id, and no field is
        # copied into a row until every field has the type the page expects.
        bad = model_contract.identity_problems(m.get("model"), "model")
        if bad:
            raise SystemExit(
                f"models.json: {manifest} has an invalid identity block; "
                f"re-export it:\n" + "\n".join(f"  - {p}" for p in bad))
        ident = m["model"]
        model_id = ident["id"]
        if model_id in seen:
            raise SystemExit(
                f"models.json: id {model_id!r} is published by both "
                f"{seen[model_id]} and {rel(d)}; a page selecting by id could "
                f"reach only one. A copied manifest keeps its old id.")
        seen[model_id] = rel(d)

        lods, primary = levels_for(d / "export", model_id)
        if "lod0" not in lods and primary is None:
            raise SystemExit(
                f"models.json: {d.name} has no full-detail .glb (neither "
                f"{model_id}.glb nor {model_id}_lod0.glb)")

        thumb = ident.get("thumbnail")
        row = {
            "id": model_id,
            "name": ident["name"],
            "area_sf": ident["area_sf"],
            "area_key": ident["area_key"],
            "area_source": ident["area_source"],
            "storeys": ident["storeys"],
            "dir": rel(d),
            "manifest": rel(manifest),
            "levels": {k: rel(v) for k, v in sorted(lods.items())},
            "primary": rel(primary) if primary else None,
            "thumbnail": rel(d / thumb) if thumb else None,
        }
        # The generator holds itself to the contract the verifier applies, so
        # a row this writes can never be one verify_index.py rejects.
        bad = model_contract.row_problems(row)
        if bad:
            raise SystemExit("models.json: built an invalid row:\n"
                             + "\n".join(f"  - {p}" for p in bad))
        rows.append(row)
    return rows


def unexported():
    """Model directories that have a spec and no published manifest.

    THE SCAN SKIPS THESE, AND SKIPPING MUST NOT BE SILENT. A directory with a
    `spec.yaml` is a model somebody meant to ship; without
    `export/variants.json` it is either never exported or an export whose
    gates failed. Leaving it off the index is right -- the page would offer a
    card that cannot load -- but #106 calls a model on disk and missing from
    the index an export failure, so it is reported, and `verify_index.py`
    fails on it.
    """
    if not MODELS.is_dir():
        return []
    return [d.name for d in sorted(p for p in MODELS.iterdir() if p.is_dir())
            if (d / "spec.yaml").is_file()
            and not (d / "export" / "variants.json").is_file()]


def rel(p: Path) -> str:
    """A path as the page resolves it: relative to the index's directory."""
    return Path(os.path.relpath(p.resolve(), INDEX.parent)).as_posix()


def build():
    return {"note": NOTE, "models": scan()}


def main():
    fresh = build()
    for name in unexported():
        print(f"WARN  {name} has spec.yaml but no export/variants.json -- "
              f"not indexed; export it or its gates failed")
    if "--check" in sys.argv:
        if not INDEX.is_file():
            print(f"FAIL  {INDEX.name} does not exist; run build_index.py")
            return 1
        try:
            have = json.loads(INDEX.read_text())
        except (ValueError, OSError) as e:
            print(f"FAIL  {INDEX.name} is unreadable or not valid JSON: {e}")
            return 1
        rows = have.get("models") if isinstance(have, dict) else None
        if not isinstance(rows, list):
            print(f"FAIL  {INDEX.name} is not an object with a `models` list; "
                  f"run build_index.py")
            return 1
        bad = [p for i, r in enumerate(rows)
               for p in model_contract.row_problems(r, f"row {i}")]
        if bad:
            print(f"FAIL  {INDEX.name} has malformed rows; run build_index.py")
            for p in bad:
                print(f"        {p}")
            return 1
        # THE WHOLE DOCUMENT, not just the rows: the note is generated too,
        # and a hand-edited one is exactly the drift this check exists for.
        if have != fresh:
            hi = {r["id"] for r in rows}
            fi = {r["id"] for r in fresh["models"]}
            print(f"FAIL  {INDEX.name} is stale — re-run build_index.py")
            for extra in sorted(fi - hi):
                print(f"        on disk but not indexed: {extra}")
            for gone in sorted(hi - fi):
                print(f"        indexed but not on disk: {gone}")
            if hi == fi:
                print(f"        same models, changed rows or note")
            return 1
        print(f"PASS  {INDEX.name} matches a fresh scan "
              f"({len(fresh['models'])} model(s))")
        return 0

    INDEX.parent.mkdir(exist_ok=True)
    INDEX.write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"wrote {INDEX.relative_to(HERE)} — {len(fresh['models'])} model(s)")
    for r in fresh["models"]:
        lv = ", ".join(sorted(r["levels"])) or "none"
        print(f"  {r['id']:<20} {r['name']:<14} "
              f"{r['area_sf']:>5} sf   levels: {lv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
