"""
build_index.py — generate models.json, the page's list of what exists.

    python3 build_index.py [--check]

The page must never be told which buildings exist. It fetches `models.json`
from a known path and renders whatever is in it, so adding Laurel is a row of
data rather than an edit to the viewer.

WHAT THIS SCANS, AND WHY IT IS NOT THE SPECS. One model per directory under
`models/`, and a model counts as PUBLISHED when it has `export/variants.json`
-- the artefact `finish_adu.py` only writes after its own gates pass. A model
whose export failed, or that has never been exported, is not in the index and
should not be: the page would offer a card that cannot load.

Every path published here is relative to THIS FILE's directory, because that
is where `models.json` sits and a relative path with no stated origin is a
path that works on one machine.

Run with `--check` to compare the index on disk against a fresh scan without
writing. That is what `verify_index.py` calls, and it is the whole point: the
index is a COMMITTED artefact, so the failure mode is not a bad scan, it is a
STALE FILE -- somebody added a model and did not re-run this.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODELS = HERE / "models"
INDEX = HERE / "models.json"

NOTE = (
    "GENERATED BY build_index.py -- do not hand-edit. A model appears here "
    "when it has export/variants.json, which finish_adu.py writes only after "
    "its gates pass. Paths are relative to this file. `levels` is ordered "
    "coarsest-last: lod0 is full detail, lod2 is massing only. `primary` is "
    "the unsuffixed .glb, a copy of lod0, kept for anyone who wants one file."
)


def levels_for(export: Path, model_id: str):
    """The .glb files this model actually shipped, classified by name.

    READ OFF DISK RATHER THAN OFF THE SPEC. The spec's `lod.levels` block
    says what SHOULD exist; this index is a promise that a URL resolves, and
    only the directory can make that promise. A spec that declares lod3 and
    an export that never wrote it would otherwise publish a 404.
    """
    found, primary = {}, None
    for glb in sorted(export.glob("*.glb")):
        stem = glb.stem
        if stem == model_id:
            primary = glb
            continue
        if stem.startswith(model_id + "_lod"):
            found[stem[len(model_id) + 1:]] = glb
    return found, primary


def scan():
    rows, seen = [], {}
    if not MODELS.is_dir():
        return rows
    for d in sorted(p for p in MODELS.iterdir() if p.is_dir()):
        manifest = d / "export" / "variants.json"
        if not manifest.is_file():
            continue
        try:
            m = json.loads(manifest.read_text())
        except (ValueError, OSError) as e:
            # ANYTHING READ FROM DISK IS UNTRUSTED INPUT, INCLUDING OUR OWN
            # FILES (rule 25). A half-written manifest must fail loudly here
            # rather than produce a row with holes in it.
            raise SystemExit(f"models.json: {manifest} is unreadable: {e}")

        if not isinstance(m, dict):
            raise SystemExit(
                f"models.json: {manifest} is valid JSON but its root is a "
                f"{type(m).__name__}, not an object")
        ident = m.get("model")
        if not isinstance(ident, dict):
            raise SystemExit(
                f"models.json: {manifest} has no `model` identity block "
                f"(found {type(ident).__name__}). Re-export it: finish_adu.py "
                f"publishes the block this index is built from.")

        # NO FALLBACK TO THE DIRECTORY NAME. The id is the key the page
        # looks models up by; substituting `d.name` would make a manifest
        # with no identity look valid and publish a filesystem fact as one.
        model_id = ident.get("id")
        if not isinstance(model_id, str) or not model_id.strip():
            raise SystemExit(
                f"models.json: {manifest} has no usable `model.id` "
                f"(found {model_id!r}). Re-export it.")
        if model_id in seen:
            raise SystemExit(
                f"models.json: id {model_id!r} is published by both "
                f"{seen[model_id]} and {rel(d)}; a page selecting by id could "
                f"reach only one. A copied manifest keeps its old id.")
        seen[model_id] = rel(d)
        lods, primary = levels_for(d / "export", model_id)
        if not lods and not primary:
            raise SystemExit(
                f"models.json: {d.name} has a manifest but no .glb beside it")

        thumb = ident.get("thumbnail")
        rows.append({
            "id": model_id,
            "name": ident.get("name"),
            "area_sf": ident.get("area_sf"),
            "area_key": ident.get("area_key"),
            "area_source": ident.get("area_source"),
            "storeys": ident.get("storeys"),
            "dir": rel(d),
            "manifest": rel(manifest),
            "levels": {k: rel(v) for k, v in sorted(lods.items())},
            "primary": rel(primary) if primary else None,
            "thumbnail": rel(d / thumb) if thumb else None,
        })
    return rows


def unexported():
    """Model directories that have a spec and no published manifest.

    THE SCAN SKIPS THESE, AND SKIPPING MUST NOT BE SILENT. A directory with a
    `spec.yaml` is a model somebody meant to ship; without
    `export/variants.json` it is either never exported or an export whose
    gates failed. Leaving it off the index is right -- the page would offer a
    card that cannot load -- but #106 calls a model on disk and missing from
    the index an export failure, so it is reported, and `verify_index.py`
    fails on it.
    """
    if not MODELS.is_dir():
        return []
    return [d.name for d in sorted(p for p in MODELS.iterdir() if p.is_dir())
            if (d / "spec.yaml").is_file()
            and not (d / "export" / "variants.json").is_file()]


def rel(p: Path) -> str:
    return p.resolve().relative_to(HERE).as_posix()


def build():
    return {"note": NOTE, "models": scan()}


def main():
    fresh = build()
    for name in unexported():
        print(f"WARN  {name} has spec.yaml but no export/variants.json -- "
              f"not indexed; export it or its gates failed")
    if "--check" in sys.argv:
        if not INDEX.is_file():
            print(f"FAIL  {INDEX.name} does not exist; run build_index.py")
            return 1
        try:
            have = json.loads(INDEX.read_text())
        except ValueError as e:
            print(f"FAIL  {INDEX.name} is not valid JSON: {e}")
            return 1
        rows = have.get("models") if isinstance(have, dict) else None
        if not isinstance(rows, list) or not all(isinstance(r, dict)
                                                 for r in rows):
            print(f"FAIL  {INDEX.name} is not an object with a `models` list "
                  f"of objects; run build_index.py")
            return 1
        # THE WHOLE DOCUMENT, not just the rows: the note is generated too,
        # and a hand-edited one is exactly the drift this check exists for.
        if have != fresh:
            hi = {r.get("id") for r in rows}
            fi = {r["id"] for r in fresh["models"]}
            print(f"FAIL  {INDEX.name} is stale — re-run build_index.py")
            for extra in sorted(fi - hi):
                print(f"        on disk but not indexed: {extra}")
            for gone in sorted(hi - fi):
                print(f"        indexed but not on disk: {gone}")
            if hi == fi:
                print(f"        same models, changed rows or note")
            return 1
        print(f"PASS  {INDEX.name} matches a fresh scan "
              f"({len(fresh['models'])} model(s))")
        return 0

    INDEX.write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"wrote {rel(INDEX)} — {len(fresh['models'])} model(s)")
    for r in fresh["models"]:
        lv = ", ".join(sorted(r["levels"])) or "none"
        print(f"  {r['id']:<20} {r['name'] or '(unnamed)':<14} "
              f"{r['area_sf'] or '?':>5} sf   levels: {lv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
