"""#111 — the fixtures that stand in for a model with parts missing, and the
rule that the fixture directory is exactly what make_fixtures.py generates
(verify_prototype.py gate 3 and `make_fixtures.py --check`)."""
from pathlib import Path

from suite import (Case, ContractCase, Run, edit, existing, fixture_export,
                   manifest, page_gates, read_json, write)

G = "#111 fixtures"
REDUCED = "models/fixture_barn_reduced/export/variants.json"


def _reduced(root: Path) -> Path:
    return fixture_export(root, "fixture_barn_reduced") / "variants.json"


def _bare(root: Path) -> Path:
    return fixture_export(root, "fixture_bare_box") / "variants.json"


def _check(fails: bool = True) -> list:
    return [Run("prototype/fixtures/make_fixtures.py", ("--check",), fails)]


def _leftover_fixture(root: Path) -> None:
    # A fixture that was removed from make_fixtures.py but not from disk.
    d = root / "prototype" / "fixtures" / "models" / "fixture_retired" / "export"
    d.mkdir(parents=True)
    (d / "variants.json").write_text('{"model": {"id": "fixture_retired"}}\n')


def _bare_is_only_model(mc, root: Path) -> list:
    keys = sorted(read_json(_bare(root)))
    return [] if keys == ["model"] else [f"the identity-only fixture has keys {keys}"]


CASES = [
    Case(G, "the reduced fixture is hand-edited",
         edit(_reduced, lambda m: m["views"].pop()),
         page_gates(), f"fixture {REDUCED} differs from what make_fixtures.py generates"),
    Case(G, "the barn cabin manifest changes and the fixtures are not regenerated",
         edit(manifest, lambda m: m["sets"][0].__setitem__("label", "Colour scheme")),
         page_gates(), f"fixture {REDUCED} differs from what make_fixtures.py generates"),
    Case(G, "the identity-only fixture gains a block",
         edit(_bare, lambda m: m.__setitem__("sets", [])),
         page_gates(), "fixture models/fixture_bare_box/export/variants.json differs"),
    Case(G, "a generated fixture file is deleted",
         lambda root: existing(_reduced(root)).unlink(),
         page_gates(), f"fixture {REDUCED} is missing"),
    Case(G, "a leftover fixture the generator no longer makes: verify_prototype.py",
         _leftover_fixture,
         page_gates(), "fixture models/fixture_retired/export/variants.json is not generated by make_fixtures.py"),
    Case(G, "a leftover fixture the generator no longer makes: --check",
         _leftover_fixture,
         _check(), "models/fixture_retired/export/variants.json is not generated by make_fixtures.py"),
    Case(G, "an unreadable fixture file is reported, not a traceback",
         lambda root: existing(_reduced(root)).chmod(0),
         page_gates(), f"fixture {REDUCED} is unreadable"),
    Case(G, "make_fixtures.py --check names a stale fixture",
         edit(_reduced, lambda m: m["views"].pop()),
         _check(), f"{REDUCED} differs"),
    Case(G, "the barn cabin no longer has what the reduced fixture removes",
         edit(manifest, lambda m: m.__setitem__(
             "presence", [g for g in m["presence"] if g["id"] != "porch_layout"])),
         _check(), "no longer has a `porch_layout` layout group"),
    Case(G, "the barn cabin has only three view modes",
         edit(manifest, lambda m: m.__setitem__("views", m["views"][:3])),
         _check(), "no longer has at least 4 view modes"),
    Case(G, "the barn cabin manifest is not JSON",
         write(manifest, "{oops"),
         _check(), "make_fixtures.py: the barn cabin manifest is unreadable"),
    Case(G, "the barn cabin has no finish sets: generated, not a KeyError",
         edit(manifest, lambda m: m.pop("sets")),
         _check(), f"{REDUCED} differs"),
    Case(G, "clean: every fixture matches make_fixtures.py", None,
         _check(fails=False), "fixture file(s) match make_fixtures.py"),
    ContractCase(G, "the identity-only fixture is only `model`", _bare_is_only_model),
]
