"""
make_fixtures.py — models the viewer has never seen, for #107 and #108.

    python3 prototype/fixtures/make_fixtures.py

Writes `fixtures/models.json` and two models under `fixtures/models/`. Open
the page with `?index=fixtures/models.json` to point the same viewer at them;
the model picker switches between the two.

WHY FIXTURES AND NOT LAUREL. The second real model is deferred, and #107 and
#108 each need a building that differs from the barn cabin in exactly the
ways the page must not care about:

    barn cabin (lod2)                   fixture_slab_box
    floor of the box  -0.972 m          0.000 m (slab on grade)
    about 7.6 x 6.4 x 10.1 m            about 7.0 x 3.2 x 7.9 m
    Draco-compressed                    uncompressed, no textures
    4 view modes                        3 view modes           (#108: 3 buttons)
    footprints incl. `with_porch`       no `with_porch`        (#108: the overlay
                                                                falls back, labelled)

    fixture_bare_box -- the same box, and a manifest with ONLY the identity
    block: no `views`, no `dimensions`. Neither control may appear (#108, #111).

    fixture_one_view_box -- one view mode, which hides the roof. One mode is
    not a choice, so no buttons render, but the mode is still applied: the
    roof is hidden on load (#108).

A viewer that memorised the barn cabin frames these wrong, renders four
buttons, or draws a porch that is not there. It is also plain glTF, which
proves the Draco decoder is used when a file needs it rather than assumed.

These are NOT buildings. Their identities say so, and their numbers are round.
"""
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))  # buyer/3D, for model_contract
import model_contract  # noqa: E402

FT = 0.3048

# glTF frame: Y up, front toward +Z (as the exporter writes it). x0, x1, y0, y1, z0, z1
# in metres. A 20 x 23 ft slab-on-grade box with an overhanging flat roof.
W, D = 20 * FT, 23 * FT
OVERHANG = 0.46
PARTS = [
    ("slab", (0.8, 0.8, 0.78), (-0.15, W + 0.15, 0.0, 0.10, -D - 0.15, 0.15)),
    ("walls", (0.62, 0.66, 0.6), (0.0, W, 0.10, 2.90, -D, 0.0)),
    ("roof", (0.2, 0.2, 0.21), (-OVERHANG, W + OVERHANG, 2.90, 3.15,
                                -D - OVERHANG, OVERHANG)),
]


def identity(model_id, name, note):
    return {
        "id": model_id,
        "name": name,
        "area_sf": 460,
        "area_key": "fixture_envelope",
        "area_source": "fixture, not a building: 20 ft x 23 ft",
        "storeys": {"count": 1, "loft": False},
        "thumbnail": None,
        "note": note,
    }


MODELS = [
    {
        "identity": identity(
            "fixture_slab_box", "Fixture: slab-on-grade box",
            "A test fixture for the viewer (#107, #108), generated by "
            "prototype/fixtures/make_fixtures.py. Not a real model."),
        "views": [
            {"id": "exterior", "label": "Exterior", "default": True, "hide": []},
            {"id": "no_roof", "label": "Roof off",
             "desc": "The roof removed.", "hide": ["fixture_roof"]},
            {"id": "slab_only", "label": "Slab only",
             "desc": "Walls and roof removed.", "hide": ["fixture_walls", "fixture_roof"]},
        ],
        # No `with_porch`: the overlay must fall back and say which it drew.
        # Both footprints are symmetric in the box, so centring places them.
        "dimensions": {
            "units": "feet",
            "main_body": {"width": 20.0, "depth": 23.0,
                          "note": "fixture: the wall box"},
            "overall": {"width": round(20 + 2 * OVERHANG / FT, 2),
                        "depth": round(23 + 2 * OVERHANG / FT, 2),
                        "note": "fixture: over the roof overhang"},
            "height_to_ridge": round(3.15 / FT, 3),
        },
    },
    {
        "identity": identity(
            "fixture_bare_box", "Fixture: bare box (identity only)",
            "A test fixture whose manifest carries only the identity block, so "
            "neither viewer control may appear (#108, #111). Not a real model."),
    },
    {
        "identity": identity(
            "fixture_one_view_box", "Fixture: one view mode",
            "A test fixture with a single view mode that hides the roof: no "
            "buttons render, and the mode is still applied (#108). Not a real "
            "model."),
        "views": [
            {"id": "roof_off", "label": "Roof off", "default": True,
             "hide": ["fixture_roof"]},
        ],
    },
]


def box_faces(x0, x1, y0, y1, z0, z1):
    """24 vertices, 36 indices, outward normals, counter-clockwise outside."""
    lo, hi = (x0, y0, z0), (x1, y1, z1)
    pos, nrm, idx = [], [], []
    for axis in range(3):
        a, b = [k for k in range(3) if k != axis]
        for side, plane in ((-1, lo[axis]), (1, hi[axis])):
            corners = []
            for ua, ub in ((0, 0), (1, 0), (1, 1), (0, 1)):
                p = [0.0, 0.0, 0.0]
                p[axis] = plane
                p[a] = (lo, hi)[ua][a]
                p[b] = (lo, hi)[ub][b]
                corners.append(p)
            e1 = [corners[1][k] - corners[0][k] for k in range(3)]
            e2 = [corners[2][k] - corners[0][k] for k in range(3)]
            cross = [e1[1] * e2[2] - e1[2] * e2[1],
                     e1[2] * e2[0] - e1[0] * e2[2],
                     e1[0] * e2[1] - e1[1] * e2[0]]
            if cross[axis] * side < 0:
                corners.reverse()
            n = [0.0, 0.0, 0.0]
            n[axis] = float(side)
            base = len(pos)
            pos += corners
            nrm += [n] * 4
            idx += [base, base + 1, base + 2, base, base + 2, base + 3]
    return pos, nrm, idx


def write_glb(path):
    gltf = {
        "asset": {"version": "2.0", "generator": "make_fixtures.py"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(PARTS)))}],
        "nodes": [], "meshes": [], "materials": [],
        "accessors": [], "bufferViews": [], "buffers": [],
    }
    blob = bytearray()

    def view(data, target):
        while len(blob) % 4:
            blob.append(0)
        gltf["bufferViews"].append({"buffer": 0, "byteOffset": len(blob),
                                    "byteLength": len(data), "target": target})
        blob.extend(data)
        return len(gltf["bufferViews"]) - 1

    for i, (name, rgb, extent) in enumerate(PARTS):
        pos, nrm, idx = box_faces(*extent)
        flat = lambda vs: b"".join(struct.pack("<3f", *v) for v in vs)
        p_view = view(flat(pos), 34962)
        n_view = view(flat(nrm), 34962)
        i_view = view(struct.pack(f"<{len(idx)}H", *idx), 34963)
        acc = len(gltf["accessors"])
        gltf["accessors"] += [
            {"bufferView": p_view, "componentType": 5126, "count": len(pos),
             "type": "VEC3", "min": [min(v[k] for v in pos) for k in range(3)],
             "max": [max(v[k] for v in pos) for k in range(3)]},
            {"bufferView": n_view, "componentType": 5126, "count": len(nrm),
             "type": "VEC3"},
            {"bufferView": i_view, "componentType": 5123, "count": len(idx),
             "type": "SCALAR"},
        ]
        gltf["materials"].append({
            "name": f"fixture_{name}",
            "pbrMetallicRoughness": {"baseColorFactor": [*rgb, 1.0],
                                     "metallicFactor": 0.0,
                                     "roughnessFactor": 0.85}})
        gltf["meshes"].append({"name": f"fixture_{name}", "primitives": [{
            "attributes": {"POSITION": acc, "NORMAL": acc + 1},
            "indices": acc + 2, "material": i}]})
        gltf["nodes"].append({"name": f"fixture_{name}", "mesh": i})

    while len(blob) % 4:
        blob.append(0)
    gltf["buffers"].append({"byteLength": len(blob)})
    js = json.dumps(gltf, separators=(",", ":")).encode()
    js += b" " * (-len(js) % 4)
    total = 12 + 8 + len(js) + 8 + len(blob)
    path.write_bytes(b"glTF" + struct.pack("<II", 2, total)
                     + struct.pack("<I", len(js)) + b"JSON" + js
                     + struct.pack("<I", len(blob)) + b"BIN\x00" + bytes(blob))


def write_model(spec):
    ident = spec["identity"]
    model_id = ident["id"]
    bad = model_contract.identity_problems(ident)
    if bad:
        raise SystemExit(f"{model_id} identity is invalid:\n" + "\n".join(bad))

    export = HERE / "models" / model_id / "export"
    export.mkdir(parents=True, exist_ok=True)
    glb = export / f"{model_id}_lod0.glb"
    write_glb(glb)

    manifest = {"model": ident,
                "note": "Fixture manifest, generated by make_fixtures.py.",
                "sets": []}
    for block in ("views", "dimensions"):
        if block in spec:
            manifest[block] = spec[block]
    # The page refuses a malformed views or dimensions block; so does this.
    bad = model_contract.display_problems(manifest)
    if bad:
        raise SystemExit(f"{model_id} manifest is invalid:\n" + "\n".join(bad))
    # Every node a view mode hides must exist in the file, as finish_adu.py
    # requires of a real export.
    _, want_nodes = model_contract.manifest_names(manifest)
    _, have_nodes = model_contract.glb_names(glb)
    if want_nodes - have_nodes:
        raise SystemExit(f"{model_id}: view modes hide nodes the file lacks: "
                         f"{sorted(want_nodes - have_nodes)}")
    (export / "variants.json").write_text(json.dumps(manifest, indent=2) + "\n")

    row = {
        "id": model_id,
        "name": ident["name"],
        "area_sf": ident["area_sf"],
        "area_key": ident["area_key"],
        "area_source": ident["area_source"],
        "storeys": ident["storeys"],
        "dir": f"models/{model_id}",
        "manifest": f"models/{model_id}/export/variants.json",
        "levels": {"lod0": f"models/{model_id}/export/{model_id}_lod0.glb"},
        "primary": None,
        "thumbnail": None,
    }
    bad = model_contract.row_problems(row)
    if bad:
        raise SystemExit(f"{model_id} row is invalid:\n" + "\n".join(bad))
    print(f"wrote {glb.relative_to(HERE)} ({glb.stat().st_size} bytes) and its "
          f"manifest ({', '.join(b for b in ('views', 'dimensions') if b in spec) or 'identity only'})")
    return row


def main():
    rows = [write_model(spec) for spec in MODELS]
    (HERE / "models.json").write_text(json.dumps({
        "note": ("GENERATED BY make_fixtures.py -- a test index for the viewer. "
                 "Open the page with ?index=fixtures/models.json. Paths are "
                 "relative to this file."),
        "models": rows,
    }, indent=2) + "\n")
    print(f"wrote models.json ({len(rows)} models)")


if __name__ == "__main__":
    main()
