"""
make_fixtures.py — a second model the viewer has never seen, for #107.

    python3 prototype/fixtures/make_fixtures.py

Writes `fixtures/models.json` and one model under `fixtures/models/`. Open
the page with `?index=fixtures/models.json` to point the same viewer at it.

WHY A FIXTURE AND NOT LAUREL. #107 is done when "a second manifest pointed at
the same viewer frames correctly with no code change", and the second real
model is deferred. So this is a building that differs from the barn cabin in
every way framing depends on:

    barn cabin (lod2)                   this fixture
    floor of the box  -0.972 m          floor of the box  0.000 m (slab on grade)
    about 7.6 x 6.4 x 10.1 m            about 7.0 x 3.2 x 7.9 m
    Draco-compressed                    uncompressed, no textures

A viewer that memorised the barn cabin frames this wrong or buries it; a
viewer that fits the box does not. It is also plain glTF, which proves the
Draco decoder is used when a file needs it rather than assumed.

It is NOT a building. Its identity says so, and its numbers are round.
"""
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))  # buyer/3D, for model_contract
import model_contract  # noqa: E402

MODEL_ID = "fixture_slab_box"
FT = 0.3048

# glTF frame: Y up, front toward +Z (as the exporter writes it). x0, x1, y0, y1, z0, z1
# in metres. A 20 x 23 ft slab-on-grade box with an overhanging flat roof.
W, D = 20 * FT, 23 * FT
PARTS = [
    ("slab", (0.8, 0.8, 0.78), (-0.15, W + 0.15, 0.0, 0.10, -D - 0.15, 0.15)),
    ("walls", (0.62, 0.66, 0.6), (0.0, W, 0.10, 2.90, -D, 0.0)),
    ("roof", (0.2, 0.2, 0.21), (-0.46, W + 0.46, 2.90, 3.15, -D - 0.46, 0.46)),
]

IDENTITY = {
    "id": MODEL_ID,
    "name": "Fixture: slab-on-grade box",
    "area_sf": 460,
    "area_key": "fixture_envelope",
    "area_source": "fixture, not a building: 20 ft x 23 ft",
    "storeys": {"count": 1, "loft": False},
    "thumbnail": None,
    "note": ("A test fixture for the viewer shell (#107), generated by "
             "prototype/fixtures/make_fixtures.py. Not a real model."),
}


def box_faces(x0, x1, y0, y1, z0, z1):
    """24 vertices, 36 indices, outward normals, counter-clockwise outside."""
    lo, hi = (x0, y0, z0), (x1, y1, z1)
    pos, nrm, idx = [], [], []
    for axis in range(3):
        a, b = [k for k in range(3) if k != axis]
        for side, plane in ((-1, lo[axis]), (1, hi[axis])):
            corners = []
            for ua, ub in ((0, 0), (1, 0), (1, 1), (0, 1)):
                p = [0.0, 0.0, 0.0]
                p[axis] = plane
                p[a] = (lo, hi)[ua][a]
                p[b] = (lo, hi)[ub][b]
                corners.append(p)
            e1 = [corners[1][k] - corners[0][k] for k in range(3)]
            e2 = [corners[2][k] - corners[0][k] for k in range(3)]
            cross = [e1[1] * e2[2] - e1[2] * e2[1],
                     e1[2] * e2[0] - e1[0] * e2[2],
                     e1[0] * e2[1] - e1[1] * e2[0]]
            if cross[axis] * side < 0:
                corners.reverse()
            n = [0.0, 0.0, 0.0]
            n[axis] = float(side)
            base = len(pos)
            pos += corners
            nrm += [n] * 4
            idx += [base, base + 1, base + 2, base, base + 2, base + 3]
    return pos, nrm, idx


def write_glb(path):
    gltf = {
        "asset": {"version": "2.0", "generator": "make_fixtures.py"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(PARTS)))}],
        "nodes": [], "meshes": [], "materials": [],
        "accessors": [], "bufferViews": [], "buffers": [],
    }
    blob = bytearray()

    def view(data, target):
        while len(blob) % 4:
            blob.append(0)
        gltf["bufferViews"].append({"buffer": 0, "byteOffset": len(blob),
                                    "byteLength": len(data), "target": target})
        blob.extend(data)
        return len(gltf["bufferViews"]) - 1

    for i, (name, rgb, extent) in enumerate(PARTS):
        pos, nrm, idx = box_faces(*extent)
        flat = lambda vs: b"".join(struct.pack("<3f", *v) for v in vs)
        p_view = view(flat(pos), 34962)
        n_view = view(flat(nrm), 34962)
        i_view = view(struct.pack(f"<{len(idx)}H", *idx), 34963)
        acc = len(gltf["accessors"])
        gltf["accessors"] += [
            {"bufferView": p_view, "componentType": 5126, "count": len(pos),
             "type": "VEC3", "min": [min(v[k] for v in pos) for k in range(3)],
             "max": [max(v[k] for v in pos) for k in range(3)]},
            {"bufferView": n_view, "componentType": 5126, "count": len(nrm),
             "type": "VEC3"},
            {"bufferView": i_view, "componentType": 5123, "count": len(idx),
             "type": "SCALAR"},
        ]
        gltf["materials"].append({
            "name": f"fixture_{name}",
            "pbrMetallicRoughness": {"baseColorFactor": [*rgb, 1.0],
                                     "metallicFactor": 0.0,
                                     "roughnessFactor": 0.85}})
        gltf["meshes"].append({"name": f"fixture_{name}", "primitives": [{
            "attributes": {"POSITION": acc, "NORMAL": acc + 1},
            "indices": acc + 2, "material": i}]})
        gltf["nodes"].append({"name": f"fixture_{name}", "mesh": i})

    while len(blob) % 4:
        blob.append(0)
    gltf["buffers"].append({"byteLength": len(blob)})
    js = json.dumps(gltf, separators=(",", ":")).encode()
    js += b" " * (-len(js) % 4)
    total = 12 + 8 + len(js) + 8 + len(blob)
    path.write_bytes(b"glTF" + struct.pack("<II", 2, total)
                     + struct.pack("<I", len(js)) + b"JSON" + js
                     + struct.pack("<I", len(blob)) + b"BIN\x00" + bytes(blob))


def main():
    export = HERE / "models" / MODEL_ID / "export"
    export.mkdir(parents=True, exist_ok=True)
    glb = export / f"{MODEL_ID}_lod0.glb"
    write_glb(glb)
    manifest = export / "variants.json"
    bad = model_contract.identity_problems(IDENTITY)
    if bad:
        raise SystemExit("fixture identity is invalid:\n" + "\n".join(bad))
    manifest.write_text(json.dumps({
        "model": IDENTITY,
        "note": "Fixture manifest: identity only, no sets, presence or views.",
        "sets": [],
    }, indent=2) + "\n")

    row = {
        "id": MODEL_ID,
        "name": IDENTITY["name"],
        "area_sf": IDENTITY["area_sf"],
        "area_key": IDENTITY["area_key"],
        "area_source": IDENTITY["area_source"],
        "storeys": IDENTITY["storeys"],
        "dir": f"models/{MODEL_ID}",
        "manifest": f"models/{MODEL_ID}/export/variants.json",
        "levels": {"lod0": f"models/{MODEL_ID}/export/{MODEL_ID}_lod0.glb"},
        "primary": None,
        "thumbnail": None,
    }
    bad = model_contract.row_problems(row)
    if bad:
        raise SystemExit("fixture row is invalid:\n" + "\n".join(bad))
    (HERE / "models.json").write_text(json.dumps({
        "note": ("GENERATED BY make_fixtures.py -- a test index for the viewer "
                 "shell. Open the page with ?index=fixtures/models.json. Paths "
                 "are relative to this file."),
        "models": [row],
    }, indent=2) + "\n")
    print(f"wrote {glb.relative_to(HERE)} ({glb.stat().st_size} bytes), "
          f"{manifest.relative_to(HERE)}, models.json")


if __name__ == "__main__":
    main()
