"""
make_fixtures.py — models the viewer has never seen, for #107, #108 and #109.

    python3 prototype/fixtures/make_fixtures.py

Writes `fixtures/models.json` and three models under `fixtures/models/`. Open
the page with `?index=fixtures/models.json` to point the same viewer at them;
the model picker switches between them.

WHY FIXTURES AND NOT LAUREL. The second real model is deferred, and the page
issues each need a building that differs from the barn cabin in exactly the
ways the page must not care about:

    barn cabin (lod2)                   fixture_slab_box
    floor of the box  -0.972 m          0.000 m (slab on grade)
    about 7.6 x 6.4 x 10.1 m            about 7.0 x 3.2 x 8.8 m
    Draco-compressed                    uncompressed, no textures
    4 view modes                        3 view modes           (#108: 3 buttons)
    footprints incl. `with_porch`       no `with_porch`        (#108: the overlay
                                                                falls back, labelled)
    8 finish sets, 3 layout groups      2 finish sets, 1 layout group, other
                                        ids and labels         (#109: the rail
                                                                renders what exists)

    fixture_bare_box -- the same box, and a manifest with ONLY the identity
    block: no `views`, no `dimensions`, no rail. No control may appear
    (#108, #109, #111).

    fixture_one_view_box -- one view mode, which hides the roof. One mode is
    not a choice, so no buttons render, but the mode is still applied: the
    roof is hidden on load (#108).

A viewer that memorised the barn cabin frames these wrong, renders four
buttons, draws a porch that is not there, or offers eight finishes. It is also
plain glTF, which proves the Draco decoder is used when a file needs it rather
than assumed.

These are NOT buildings. Their identities say so, and their numbers are round.
"""
import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]))  # buyer/3D, for model_contract
import model_contract  # noqa: E402

FT = 0.3048

# glTF frame: Y up, front toward +Z (as the exporter writes it). x0, x1, y0, y1, z0, z1
# in metres. A 20 x 23 ft slab-on-grade box with an overhanging flat roof.
W, D = 20 * FT, 23 * FT
OVERHANG = 0.46
PARTS = [
    ("slab", (0.8, 0.8, 0.78), (-0.15, W + 0.15, 0.0, 0.10, -D - 0.15, 0.15)),
    ("walls", (0.62, 0.66, 0.6), (0.0, W, 0.10, 2.90, -D, 0.0)),
    ("roof", (0.2, 0.2, 0.21), (-OVERHANG, W + OVERHANG, 2.90, 3.15,
                                -D - OVERHANG, OVERHANG)),
]
# Something a layout can show or hide: a bench in front of the entry.
BENCH = ("bench", (0.45, 0.33, 0.2), (1.0, 2.4, 0.10, 0.55, 0.6, 1.0))


def identity(model_id, name, note):
    return {
        "id": model_id,
        "name": name,
        "area_sf": 460,
        "area_key": "fixture_envelope",
        "area_source": "fixture, not a building: 20 ft x 23 ft",
        "storeys": {"count": 1, "loft": False},
        "thumbnail": None,
        "note": note,
    }


MODELS = [
    {
        "identity": identity(
            "fixture_slab_box", "Fixture: slab-on-grade box",
            "A test fixture for the viewer (#107, #108, #109), generated by "
            "prototype/fixtures/make_fixtures.py. Not a real model."),
        "parts": PARTS + [BENCH],
        # Two finish sets with ids, labels and counts the barn cabin does not
        # have. The first option of each matches the colour baked into the
        # file, as a real export's defaults do.
        "sets": [
            {"id": "wall_colour", "label": "Wall colour", "property": "baseColorFactor",
             "targets": ["fixture_walls"],
             "options": [
                 {"id": "pale", "label": "Pale green", "value": [0.62, 0.66, 0.6, 1.0], "default": True},
                 {"id": "clay", "label": "Clay", "value": [0.45, 0.25, 0.18, 1.0]},
                 {"id": "ink", "label": "Ink", "value": [0.05, 0.06, 0.08, 1.0]},
             ]},
            {"id": "roof_tone", "label": "Roof tone", "property": "baseColorFactor",
             "targets": ["fixture_roof"],
             "options": [
                 {"id": "dark_roof", "label": "Dark", "value": [0.2, 0.2, 0.21, 1.0], "default": True},
                 {"id": "light_roof", "label": "Light", "value": [0.7, 0.7, 0.68, 1.0]},
             ]},
        ],
        "presence": [
            {"id": "entry_seating", "label": "Entry seating", "room": "forecourt",
             "property": "visible",
             "options": [
                 {"id": "with_bench", "label": "With bench", "default": True,
                  "show": ["fixture_bench"]},
                 {"id": "no_bench", "label": "No bench", "show": []},
             ]},
        ],
        "disclosure": "Fixture: the bench is shown for scale; not included.",
        "views": [
            {"id": "exterior", "label": "Exterior", "default": True, "hide": []},
            {"id": "no_roof", "label": "Roof off",
             "desc": "The roof removed.", "hide": ["fixture_roof"]},
            {"id": "slab_only", "label": "Slab only",
             "desc": "Walls and roof removed.", "hide": ["fixture_walls", "fixture_roof"]},
        ],
        # No `with_porch`: the overlay must fall back and say which it drew.
        # Both footprints are symmetric in the box, so centring places them.
        "dimensions": {
            "units": "feet",
            "main_body": {"width": 20.0, "depth": 23.0,
                          "note": "fixture: the wall box"},
            "overall": {"width": round(20 + 2 * OVERHANG / FT, 2),
                        "depth": round(23 + 2 * OVERHANG / FT, 2),
                        "note": "fixture: over the roof overhang"},
            "height_to_ridge": round(3.15 / FT, 3),
        },
    },
    {
        "identity": identity(
            "fixture_bare_box", "Fixture: bare box (identity only)",
            "A test fixture whose manifest carries only the identity block, so "
            "no viewer control and no rail may appear (#108, #109, #111). Not a "
            "real model."),
    },
    {
        "identity": identity(
            "fixture_one_view_box", "Fixture: one view mode",
            "A test fixture with a single view mode that hides the roof: no "
            "buttons render, and the mode is still applied (#108). Not a real "
            "model."),
        "views": [
            {"id": "roof_off", "label": "Roof off", "default": True,
             "hide": ["fixture_roof"]},
        ],
    },
]

MANIFEST_BLOCKS = ("sets", "presence", "disclosure", "views", "dimensions")


def box_faces(x0, x1, y0, y1, z0, z1):
    """24 vertices, 36 indices, outward normals, counter-clockwise outside."""
    lo, hi = (x0, y0, z0), (x1, y1, z1)
    pos, nrm, idx = [], [], []
    for axis in range(3):
        a, b = [k for k in range(3) if k != axis]
        for side, plane in ((-1, lo[axis]), (1, hi[axis])):
            corners = []
            for ua, ub in ((0, 0), (1, 0), (1, 1), (0, 1)):
                p = [0.0, 0.0, 0.0]
                p[axis] = plane
                p[a] = (lo, hi)[ua][a]
                p[b] = (lo, hi)[ub][b]
                corners.append(p)
            e1 = [corners[1][k] - corners[0][k] for k in range(3)]
            e2 = [corners[2][k] - corners[0][k] for k in range(3)]
            cross = [e1[1] * e2[2] - e1[2] * e2[1],
                     e1[2] * e2[0] - e1[0] * e2[2],
                     e1[0] * e2[1] - e1[1] * e2[0]]
            if cross[axis] * side < 0:
                corners.reverse()
            n = [0.0, 0.0, 0.0]
            n[axis] = float(side)
            base = len(pos)
            pos += corners
            nrm += [n] * 4
            idx += [base, base + 1, base + 2, base, base + 2, base + 3]
    return pos, nrm, idx


def write_glb(path, parts):
    gltf = {
        "asset": {"version": "2.0", "generator": "make_fixtures.py"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(parts)))}],
        "nodes": [], "meshes": [], "materials": [],
        "accessors": [], "bufferViews": [], "buffers": [],
    }
    blob = bytearray()

    def view(data, target):
        while len(blob) % 4:
            blob.append(0)
        gltf["bufferViews"].append({"buffer": 0, "byteOffset": len(blob),
                                    "byteLength": len(data), "target": target})
        blob.extend(data)
        return len(gltf["bufferViews"]) - 1

    for i, (name, rgb, extent) in enumerate(parts):
        pos, nrm, idx = box_faces(*extent)
        flat = lambda vs: b"".join(struct.pack("<3f", *v) for v in vs)
        p_view = view(flat(pos), 34962)
        n_view = view(flat(nrm), 34962)
        i_view = view(struct.pack(f"<{len(idx)}H", *idx), 34963)
        acc = len(gltf["accessors"])
        gltf["accessors"] += [
            {"bufferView": p_view, "componentType": 5126, "count": len(pos),
             "type": "VEC3", "min": [min(v[k] for v in pos) for k in range(3)],
             "max": [max(v[k] for v in pos) for k in range(3)]},
            {"bufferView": n_view, "componentType": 5126, "count": len(nrm),
             "type": "VEC3"},
            {"bufferView": i_view, "componentType": 5123, "count": len(idx),
             "type": "SCALAR"},
        ]
        gltf["materials"].append({
            "name": f"fixture_{name}",
            "pbrMetallicRoughness": {"baseColorFactor": [*rgb, 1.0],
                                     "metallicFactor": 0.0,
                                     "roughnessFactor": 0.85}})
        gltf["meshes"].append({"name": f"fixture_{name}", "primitives": [{
            "attributes": {"POSITION": acc, "NORMAL": acc + 1},
            "indices": acc + 2, "material": i}]})
        gltf["nodes"].append({"name": f"fixture_{name}", "mesh": i})

    while len(blob) % 4:
        blob.append(0)
    gltf["buffers"].append({"byteLength": len(blob)})
    js = json.dumps(gltf, separators=(",", ":")).encode()
    js += b" " * (-len(js) % 4)
    total = 12 + 8 + len(js) + 8 + len(blob)
    path.write_bytes(b"glTF" + struct.pack("<II", 2, total)
                     + struct.pack("<I", len(js)) + b"JSON" + js
                     + struct.pack("<I", len(blob)) + b"BIN\x00" + bytes(blob))


def write_model(spec):
    ident = spec["identity"]
    model_id = ident["id"]
    bad = model_contract.identity_problems(ident)
    if bad:
        raise SystemExit(f"{model_id} identity is invalid:\n" + "\n".join(bad))

    export = HERE / "models" / model_id / "export"
    export.mkdir(parents=True, exist_ok=True)
    glb = export / f"{model_id}_lod0.glb"
    write_glb(glb, spec.get("parts", PARTS))

    manifest = {"model": ident,
                "note": "Fixture manifest, generated by make_fixtures.py."}
    manifest["sets"] = spec.get("sets", [])
    for block in MANIFEST_BLOCKS:
        if block in spec:
            manifest[block] = spec[block]
    # The page refuses a malformed block; so does this.
    bad = model_contract.display_problems(manifest)
    if bad:
        raise SystemExit(f"{model_id} manifest is invalid:\n" + "\n".join(bad))
    # Every material a set tints, every node a layout shows and every node a
    # view mode hides must exist in the file, as a real export requires.
    want_mats, want_nodes = model_contract.manifest_names(manifest)
    have_mats, have_nodes = model_contract.glb_names(glb)
    if want_mats - have_mats or want_nodes - have_nodes:
        raise SystemExit(f"{model_id}: manifest names what the file lacks: "
                         f"{sorted((want_mats - have_mats) | (want_nodes - have_nodes))}")
    (export / "variants.json").write_text(json.dumps(manifest, indent=2) + "\n")

    row = {
        "id": model_id,
        "name": ident["name"],
        "area_sf": ident["area_sf"],
        "area_key": ident["area_key"],
        "area_source": ident["area_source"],
        "storeys": ident["storeys"],
        "dir": f"models/{model_id}",
        "manifest": f"models/{model_id}/export/variants.json",
        "levels": {"lod0": f"models/{model_id}/export/{model_id}_lod0.glb"},
        "primary": None,
        "thumbnail": None,
    }
    bad = model_contract.row_problems(row)
    if bad:
        raise SystemExit(f"{model_id} row is invalid:\n" + "\n".join(bad))
    blocks = [b for b in MANIFEST_BLOCKS if b in spec]
    print(f"wrote {glb.relative_to(HERE)} ({glb.stat().st_size} bytes) and its "
          f"manifest ({', '.join(blocks) or 'identity only'})")
    return row


def main():
    rows = [write_model(spec) for spec in MODELS]
    (HERE / "models.json").write_text(json.dumps({
        "note": ("GENERATED BY make_fixtures.py -- a test index for the viewer. "
                 "Open the page with ?index=fixtures/models.json. Paths are "
                 "relative to this file."),
        "models": rows,
    }, indent=2) + "\n")
    print(f"wrote models.json ({len(rows)} models)")


if __name__ == "__main__":
    main()
